# docker compose file with mongodb
version: '3.1'
services:
  mongo:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MONGO_PACKAGE: mongodb-enterprise
        MONGO_REPO: repo.mongodb.com
    ports:
      - "27017:27017"
    container_name: mongo
    restart: always
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: test